package com.example.lzc.greendaodemo.dao.userdao;

import com.example.lzc.greendaodemo.dao.NewTable;
import com.example.lzc.greendaodemo.dao.User;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newTableDaoConfig;
    private final DaoConfig userDaoConfig;

    private final UserDao userDao;
    private final NewTableDao newTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);
        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newTableDaoConfig = daoConfigMap.get(NewTableDao.class).clone();
        newTableDaoConfig.initIdentityScope(type);

        newTableDao = new NewTableDao(newTableDaoConfig, this);
        userDao = new UserDao(userDaoConfig,this);

        registerDao(NewTable.class, newTableDao);
        registerDao(User.class,userDao);
    }
    
    public void clear() {
        newTableDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public NewTableDao getNewTableDao() {
        return newTableDao;
    }

    public UserDao getUserDao(){
        return userDao;
    }

}
